apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: chat-service
spec:
  selector:
    app: chat-service
    version: blue  # default to blue version
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80 # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
      targetPort: 8080 # Порт контейнера, на котором доступно приложение.
      nodePort: 30001 # Необязательное поле. По умолчанию и для удобства плоскость управления Kubernetes выделит порт из диапазона (по умолчанию: 30000-32767).
