version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gateway-service
      - POSTGRES_USER=gateway-service
      - POSTGRES_PASSWORD=gateway-service
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gateway-service
      - POSTGRES_USER=gateway-service
      - POSTGRES_PASSWORD=gateway-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
