apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: app1
  labels:
    app: app1
spec:
  # ReplicaSet
  replicas: 3 # сколько экземляров приложения развернуть
  selector: # какие поды нужно поддерживать
    matchLabels:
      app: app1
  template: # для подов (Pod)
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1-container
          image: docker.io/library/app1:latest
          imagePullPolicy: "Never" # for local in minikube
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources: # Ресурсы pod-а
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1"
  strategy: # Стратегия
    type: RollingUpdate # Recrate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
