apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: gateway-service
spec:
  selector:
    app: gateway-service
    version: blue  # default to blue version
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
