apiVersion: v1
kind: Service
metadata:
  name: social-service
  namespace: social-service
spec:
  selector:
    app: social-service
    version: blue  # default to blue version
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 