// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AcceptFriendRequestRequest accept friend request request
//
// swagger:model AcceptFriendRequestRequest
type AcceptFriendRequestRequest struct {

	// request id
	RequestID string `json:"request_id,omitempty"`
}

// Validate validates this accept friend request request
func (m *AcceptFriendRequestRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this accept friend request request based on context it is used
func (m *AcceptFriendRequestRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AcceptFriendRequestRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcceptFriendRequestRequest) UnmarshalBinary(b []byte) error {
	var res AcceptFriendRequestRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
