// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateChatRequest create chat request
//
// swagger:model CreateChatRequest
type CreateChatRequest struct {

	// participant ids
	ParticipantIds []string `json:"participant_ids"`
}

// Validate validates this create chat request
func (m *CreateChatRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create chat request based on context it is used
func (m *CreateChatRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateChatRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateChatRequest) UnmarshalBinary(b []byte) error {
	var res CreateChatRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
