// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateChatResponse create chat response
//
// swagger:model CreateChatResponse
type CreateChatResponse struct {

	// chat id
	ChatID string `json:"chat_id,omitempty"`
}

// Validate validates this create chat response
func (m *CreateChatResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create chat response based on context it is used
func (m *CreateChatResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateChatResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateChatResponse) UnmarshalBinary(b []byte) error {
	var res CreateChatResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
