// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateFriendRequestRequest create friend request request
//
// swagger:model CreateFriendRequestRequest
type CreateFriendRequestRequest struct {

	// to user id
	ToUserID string `json:"to_user_id,omitempty"`
}

// Validate validates this create friend request request
func (m *CreateFriendRequestRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create friend request request based on context it is used
func (m *CreateFriendRequestRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateFriendRequestRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateFriendRequestRequest) UnmarshalBinary(b []byte) error {
	var res CreateFriendRequestRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
