// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateFriendRequestResponse create friend request response
//
// swagger:model CreateFriendRequestResponse
type CreateFriendRequestResponse struct {

	// request id
	RequestID string `json:"request_id,omitempty"`
}

// Validate validates this create friend request response
func (m *CreateFriendRequestResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create friend request response based on context it is used
func (m *CreateFriendRequestResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateFriendRequestResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateFriendRequestResponse) UnmarshalBinary(b []byte) error {
	var res CreateFriendRequestResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
