// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateProfileResponse create profile response
//
// swagger:model CreateProfileResponse
type CreateProfileResponse struct {

	// profile id
	ProfileID string `json:"profile_id,omitempty"`
}

// Validate validates this create profile response
func (m *CreateProfileResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create profile response based on context it is used
func (m *CreateProfileResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateProfileResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateProfileResponse) UnmarshalBinary(b []byte) error {
	var res CreateProfileResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
