// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DeclineFriendRequestResponse decline friend request response
//
// swagger:model DeclineFriendRequestResponse
type DeclineFriendRequestResponse interface{}
