// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteFriendRequest delete friend request
//
// swagger:model DeleteFriendRequest
type DeleteFriendRequest struct {

	// friend id
	FriendID string `json:"friend_id,omitempty"`
}

// Validate validates this delete friend request
func (m *DeleteFriendRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete friend request based on context it is used
func (m *DeleteFriendRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteFriendRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteFriendRequest) UnmarshalBinary(b []byte) error {
	var res DeleteFriendRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
