// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FriendRequest friend request
//
// swagger:model FriendRequest
type FriendRequest struct {

	// from user id
	FromUserID string `json:"from_user_id,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// status
	// Enum: ["PENDING","ACCEPTED","DECLINED"]
	Status string `json:"status,omitempty"`

	// to user id
	ToUserID string `json:"to_user_id,omitempty"`
}

// Validate validates this friend request
func (m *FriendRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var friendRequestTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PENDING","ACCEPTED","DECLINED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		friendRequestTypeStatusPropEnum = append(friendRequestTypeStatusPropEnum, v)
	}
}

const (

	// FriendRequestStatusPENDING captures enum value "PENDING"
	FriendRequestStatusPENDING string = "PENDING"

	// FriendRequestStatusACCEPTED captures enum value "ACCEPTED"
	FriendRequestStatusACCEPTED string = "ACCEPTED"

	// FriendRequestStatusDECLINED captures enum value "DECLINED"
	FriendRequestStatusDECLINED string = "DECLINED"
)

// prop value enum
func (m *FriendRequest) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, friendRequestTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FriendRequest) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this friend request based on context it is used
func (m *FriendRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FriendRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FriendRequest) UnmarshalBinary(b []byte) error {
	var res FriendRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
