// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetFriendsResponse get friends response
//
// swagger:model GetFriendsResponse
type GetFriendsResponse struct {

	// friends
	Friends []*Profile `json:"friends"`
}

// Validate validates this get friends response
func (m *GetFriendsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFriends(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetFriendsResponse) validateFriends(formats strfmt.Registry) error {
	if swag.IsZero(m.Friends) { // not required
		return nil
	}

	for i := 0; i < len(m.Friends); i++ {
		if swag.IsZero(m.Friends[i]) { // not required
			continue
		}

		if m.Friends[i] != nil {
			if err := m.Friends[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("friends" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("friends" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get friends response based on the context it is used
func (m *GetFriendsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFriends(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetFriendsResponse) contextValidateFriends(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Friends); i++ {

		if m.Friends[i] != nil {

			if swag.IsZero(m.Friends[i]) { // not required
				return nil
			}

			if err := m.Friends[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("friends" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("friends" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetFriendsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetFriendsResponse) UnmarshalBinary(b []byte) error {
	var res GetFriendsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
