// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetChatMessagesRequest get chat messages request
//
// swagger:model GetChatMessagesRequest
type GetChatMessagesRequest struct {

	// chat id
	ChatID string `json:"chat_id,omitempty"`
}

// Validate validates this get chat messages request
func (m *GetChatMessagesRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get chat messages request based on context it is used
func (m *GetChatMessagesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetChatMessagesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetChatMessagesRequest) UnmarshalBinary(b []byte) error {
	var res GetChatMessagesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
