// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SendMessageRequest send message request
//
// swagger:model SendMessageRequest
type SendMessageRequest struct {

	// chat id
	ChatID string `json:"chat_id,omitempty"`

	// content
	Content string `json:"content,omitempty"`
}

// Validate validates this send message request
func (m *SendMessageRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this send message request based on context it is used
func (m *SendMessageRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SendMessageRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SendMessageRequest) UnmarshalBinary(b []byte) error {
	var res SendMessageRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
