// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TokenRefreshResponse token refresh response
//
// swagger:model TokenRefreshResponse
type TokenRefreshResponse struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`

	// refresh token
	RefreshToken string `json:"refresh_token,omitempty"`
}

// Validate validates this token refresh response
func (m *TokenRefreshResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this token refresh response based on context it is used
func (m *TokenRefreshResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TokenRefreshResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TokenRefreshResponse) UnmarshalBinary(b []byte) error {
	var res TokenRefreshResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
