// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TokenRefreshRequest token refresh request
//
// swagger:model TokenRefreshRequest
type TokenRefreshRequest struct {

	// refresh token
	RefreshToken string `json:"refresh_token,omitempty"`
}

// Validate validates this token refresh request
func (m *TokenRefreshRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this token refresh request based on context it is used
func (m *TokenRefreshRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TokenRefreshRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TokenRefreshRequest) UnmarshalBinary(b []byte) error {
	var res TokenRefreshRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
