// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TokenIntrospectResponse token introspect response
//
// swagger:model TokenIntrospectResponse
type TokenIntrospectResponse struct {

	// user id
	UserID string `json:"user_id,omitempty"`

	// valid
	Valid bool `json:"valid,omitempty"`
}

// Validate validates this token introspect response
func (m *TokenIntrospectResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this token introspect response based on context it is used
func (m *TokenIntrospectResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TokenIntrospectResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TokenIntrospectResponse) UnmarshalBinary(b []byte) error {
	var res TokenIntrospectResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
