// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/user/service.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_user_service_proto protoreflect.FileDescriptor

const file_api_user_service_proto_rawDesc = "" +
	"\n" +
	"\x16api/user/service.proto\x12\x04user\x1a\x17api/user/messages.proto2\xd0\x02\n" +
	"\vUserService\x12;\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\"\x00\x122\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\"\x00\x125\n" +
	"\x06Logout\x12\x13.user.LogoutRequest\x1a\x14.user.LogoutResponse\"\x00\x12P\n" +
	"\x0fTokenIntrospect\x12\x1c.user.TokenIntrospectRequest\x1a\x1d.user.TokenIntrospectResponse\"\x00\x12G\n" +
	"\fTokenRefresh\x12\x19.user.TokenRefreshRequest\x1a\x1a.user.TokenRefreshResponse\"\x00B\x0eZ\fpkg/api/userb\x06proto3"

var file_api_user_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),         // 0: user.RegisterRequest
	(*LoginRequest)(nil),            // 1: user.LoginRequest
	(*LogoutRequest)(nil),           // 2: user.LogoutRequest
	(*TokenIntrospectRequest)(nil),  // 3: user.TokenIntrospectRequest
	(*TokenRefreshRequest)(nil),     // 4: user.TokenRefreshRequest
	(*RegisterResponse)(nil),        // 5: user.RegisterResponse
	(*LoginResponse)(nil),           // 6: user.LoginResponse
	(*LogoutResponse)(nil),          // 7: user.LogoutResponse
	(*TokenIntrospectResponse)(nil), // 8: user.TokenIntrospectResponse
	(*TokenRefreshResponse)(nil),    // 9: user.TokenRefreshResponse
}
var file_api_user_service_proto_depIdxs = []int32{
	0, // 0: user.UserService.Register:input_type -> user.RegisterRequest
	1, // 1: user.UserService.Login:input_type -> user.LoginRequest
	2, // 2: user.UserService.Logout:input_type -> user.LogoutRequest
	3, // 3: user.UserService.TokenIntrospect:input_type -> user.TokenIntrospectRequest
	4, // 4: user.UserService.TokenRefresh:input_type -> user.TokenRefreshRequest
	5, // 5: user.UserService.Register:output_type -> user.RegisterResponse
	6, // 6: user.UserService.Login:output_type -> user.LoginResponse
	7, // 7: user.UserService.Logout:output_type -> user.LogoutResponse
	8, // 8: user.UserService.TokenIntrospect:output_type -> user.TokenIntrospectResponse
	9, // 9: user.UserService.TokenRefresh:output_type -> user.TokenRefreshResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_user_service_proto_init() }
func file_api_user_service_proto_init() {
	if File_api_user_service_proto != nil {
		return
	}
	file_api_user_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_service_proto_rawDesc), len(file_api_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_service_proto_goTypes,
		DependencyIndexes: file_api_user_service_proto_depIdxs,
	}.Build()
	File_api_user_service_proto = out.File
	file_api_user_service_proto_goTypes = nil
	file_api_user_service_proto_depIdxs = nil
}
