// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/social/service.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_social_service_proto protoreflect.FileDescriptor

const file_api_social_service_proto_rawDesc = "" +
	"\n" +
	"\x18api/social/service.proto\x12\x06social\x1a\x19api/social/messages.proto2\xcb\x05\n" +
	"\rSocialService\x12N\n" +
	"\rCreateProfile\x12\x1c.social.CreateProfileRequest\x1a\x1d.social.CreateProfileResponse\"\x00\x12Q\n" +
	"\x0eSearchProfiles\x12\x1d.social.SearchProfilesRequest\x1a\x1e.social.SearchProfilesResponse\"\x00\x12`\n" +
	"\x13CreateFriendRequest\x12\".social.CreateFriendRequestRequest\x1a#.social.CreateFriendRequestResponse\"\x00\x12Z\n" +
	"\x11GetFriendRequests\x12 .social.GetFriendRequestsRequest\x1a!.social.GetFriendRequestsResponse\"\x00\x12`\n" +
	"\x13AcceptFriendRequest\x12\".social.AcceptFriendRequestRequest\x1a#.social.AcceptFriendRequestResponse\"\x00\x12c\n" +
	"\x14DeclineFriendRequest\x12#.social.DeclineFriendRequestRequest\x1a$.social.DeclineFriendRequestResponse\"\x00\x12E\n" +
	"\n" +
	"GetFriends\x12\x19.social.GetFriendsRequest\x1a\x1a.social.GetFriendsResponse\"\x00\x12K\n" +
	"\fDeleteFriend\x12\x1b.social.DeleteFriendRequest\x1a\x1c.social.DeleteFriendResponse\"\x00B\x10Z\x0epkg/api/socialb\x06proto3"

var file_api_social_service_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),         // 0: social.CreateProfileRequest
	(*SearchProfilesRequest)(nil),        // 1: social.SearchProfilesRequest
	(*CreateFriendRequestRequest)(nil),   // 2: social.CreateFriendRequestRequest
	(*GetFriendRequestsRequest)(nil),     // 3: social.GetFriendRequestsRequest
	(*AcceptFriendRequestRequest)(nil),   // 4: social.AcceptFriendRequestRequest
	(*DeclineFriendRequestRequest)(nil),  // 5: social.DeclineFriendRequestRequest
	(*GetFriendsRequest)(nil),            // 6: social.GetFriendsRequest
	(*DeleteFriendRequest)(nil),          // 7: social.DeleteFriendRequest
	(*CreateProfileResponse)(nil),        // 8: social.CreateProfileResponse
	(*SearchProfilesResponse)(nil),       // 9: social.SearchProfilesResponse
	(*CreateFriendRequestResponse)(nil),  // 10: social.CreateFriendRequestResponse
	(*GetFriendRequestsResponse)(nil),    // 11: social.GetFriendRequestsResponse
	(*AcceptFriendRequestResponse)(nil),  // 12: social.AcceptFriendRequestResponse
	(*DeclineFriendRequestResponse)(nil), // 13: social.DeclineFriendRequestResponse
	(*GetFriendsResponse)(nil),           // 14: social.GetFriendsResponse
	(*DeleteFriendResponse)(nil),         // 15: social.DeleteFriendResponse
}
var file_api_social_service_proto_depIdxs = []int32{
	0,  // 0: social.SocialService.CreateProfile:input_type -> social.CreateProfileRequest
	1,  // 1: social.SocialService.SearchProfiles:input_type -> social.SearchProfilesRequest
	2,  // 2: social.SocialService.CreateFriendRequest:input_type -> social.CreateFriendRequestRequest
	3,  // 3: social.SocialService.GetFriendRequests:input_type -> social.GetFriendRequestsRequest
	4,  // 4: social.SocialService.AcceptFriendRequest:input_type -> social.AcceptFriendRequestRequest
	5,  // 5: social.SocialService.DeclineFriendRequest:input_type -> social.DeclineFriendRequestRequest
	6,  // 6: social.SocialService.GetFriends:input_type -> social.GetFriendsRequest
	7,  // 7: social.SocialService.DeleteFriend:input_type -> social.DeleteFriendRequest
	8,  // 8: social.SocialService.CreateProfile:output_type -> social.CreateProfileResponse
	9,  // 9: social.SocialService.SearchProfiles:output_type -> social.SearchProfilesResponse
	10, // 10: social.SocialService.CreateFriendRequest:output_type -> social.CreateFriendRequestResponse
	11, // 11: social.SocialService.GetFriendRequests:output_type -> social.GetFriendRequestsResponse
	12, // 12: social.SocialService.AcceptFriendRequest:output_type -> social.AcceptFriendRequestResponse
	13, // 13: social.SocialService.DeclineFriendRequest:output_type -> social.DeclineFriendRequestResponse
	14, // 14: social.SocialService.GetFriends:output_type -> social.GetFriendsResponse
	15, // 15: social.SocialService.DeleteFriend:output_type -> social.DeleteFriendResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_social_service_proto_init() }
func file_api_social_service_proto_init() {
	if File_api_social_service_proto != nil {
		return
	}
	file_api_social_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_social_service_proto_rawDesc), len(file_api_social_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_social_service_proto_goTypes,
		DependencyIndexes: file_api_social_service_proto_depIdxs,
	}.Build()
	File_api_social_service_proto = out.File
	file_api_social_service_proto_goTypes = nil
	file_api_social_service_proto_depIdxs = nil
}
