// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/service.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_service_proto protoreflect.FileDescriptor

const file_api_service_proto_rawDesc = "" +
	"\n" +
	"\x11api/service.proto\x12\x04chat\x1a\x12api/messages.proto2\xab\x02\n" +
	"\vChatService\x12A\n" +
	"\n" +
	"CreateChat\x12\x17.chat.CreateChatRequest\x1a\x18.chat.CreateChatResponse\"\x00\x12A\n" +
	"\n" +
	"DeleteChat\x12\x17.chat.DeleteChatRequest\x1a\x18.chat.DeleteChatResponse\"\x00\x12P\n" +
	"\x0fGetChatMessages\x12\x1c.chat.GetChatMessagesRequest\x1a\x1d.chat.GetChatMessagesResponse\"\x00\x12D\n" +
	"\vSendMessage\x12\x18.chat.SendMessageRequest\x1a\x19.chat.SendMessageResponse\"\x00B\x0eZ\fpkg/api/chatb\x06proto3"

var file_api_service_proto_goTypes = []any{
	(*CreateChatRequest)(nil),       // 0: chat.CreateChatRequest
	(*DeleteChatRequest)(nil),       // 1: chat.DeleteChatRequest
	(*GetChatMessagesRequest)(nil),  // 2: chat.GetChatMessagesRequest
	(*SendMessageRequest)(nil),      // 3: chat.SendMessageRequest
	(*CreateChatResponse)(nil),      // 4: chat.CreateChatResponse
	(*DeleteChatResponse)(nil),      // 5: chat.DeleteChatResponse
	(*GetChatMessagesResponse)(nil), // 6: chat.GetChatMessagesResponse
	(*SendMessageResponse)(nil),     // 7: chat.SendMessageResponse
}
var file_api_service_proto_depIdxs = []int32{
	0, // 0: chat.ChatService.CreateChat:input_type -> chat.CreateChatRequest
	1, // 1: chat.ChatService.DeleteChat:input_type -> chat.DeleteChatRequest
	2, // 2: chat.ChatService.GetChatMessages:input_type -> chat.GetChatMessagesRequest
	3, // 3: chat.ChatService.SendMessage:input_type -> chat.SendMessageRequest
	4, // 4: chat.ChatService.CreateChat:output_type -> chat.CreateChatResponse
	5, // 5: chat.ChatService.DeleteChat:output_type -> chat.DeleteChatResponse
	6, // 6: chat.ChatService.GetChatMessages:output_type -> chat.GetChatMessagesResponse
	7, // 7: chat.ChatService.SendMessage:output_type -> chat.SendMessageResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_service_proto_init() }
func file_api_service_proto_init() {
	if File_api_service_proto != nil {
		return
	}
	file_api_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_proto_goTypes,
		DependencyIndexes: file_api_service_proto_depIdxs,
	}.Build()
	File_api_service_proto = out.File
	file_api_service_proto_goTypes = nil
	file_api_service_proto_depIdxs = nil
}
