syntax = "proto3";
package social;
option go_package = "pkg/api/social";

message Profile {
  string user_id = 1;
  string nickname = 2;
  optional string first_name = 3;
  optional string last_name = 4;
  optional string email = 5;
}

message CreateProfileRequest {
  string user_id = 1;
  string nickname = 2;
  optional string first_name = 3;
  optional string last_name = 4;
  optional string email = 5;
}

message CreateProfileResponse {
  string id = 1;
  string user_id = 2;
  string nickname = 3;
  optional string first_name = 4;
  optional string last_name = 5;
  optional string email = 6;
}

message SearchProfilesRequest {
  string nickname = 1;
}

message SearchProfilesResponse {
  repeated Profile profiles = 1;
}

message FriendRequest {
  string user_id = 1;
  string friend_id = 2;
}

message CreateFriendRequestRequest {
  string user_id = 1;
  string friend_id = 2;
}

message CreateFriendRequestResponse {
  bool success = 1;
}

message GetFriendRequestsRequest {
  string user_id = 1;
}

message GetFriendRequestsResponse {
  repeated FriendRequest requests = 1;
}

message AcceptFriendRequestRequest {
  string user_id = 1;
  string friend_id = 2;
}

message AcceptFriendRequestResponse {
  bool success = 1;
}

message DeclineFriendRequestRequest {
  string user_id = 1;
  string friend_id = 2;
}

message DeclineFriendRequestResponse {
  bool success = 1;
}

message GetFriendsRequest {
  string user_id = 1;
}

message GetFriendsResponse {
  repeated string friend_ids = 1;
}

message DeleteFriendRequest {
  string user_id = 1;
  string friend_id = 2;
}

message DeleteFriendResponse {
  bool success = 1;
}
